### PR TITLE
extended "Array Methods" section

### PR DESCRIPTION
**Pull request by RinatValiullov**
added notes and example about `reduce` method and initialValue

### CODE REVIEW

**Comment by nas5w** [comment]
It looks like a lot of single quotes were changed to double quotes during this change. Can you undo that? The guide uses a single quote style.

**Comment by RinatValiullov** [comment]
> It looks like a lot of single quotes were changed to double quotes during this change. Can you undo that? The guide uses a single quote style.

Change double quotes to single? No problem.

**Comment by RinatValiullov** [comment]
@nas5w
Done. Check, please.

**Comment by nas5w** [comment]
Thanks, merged!

**Pull request merged**
